fontFamily: "'Inter', sans-serif",
  },
  headerTitle: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 700,
    fontSize: 64,
    color: '#FFFFFF',
    lineHeight: 0.9,
    letterSpacing: '-2px',
    margin: 0,
    textShadow: '0 0 30px rgba(204,255,0,0.25)',
  },
  nav: {
    position: 'sticky',
    top: 12,
    zIndex: 100,
    padding: '0 16px',
    marginBottom: 8,
  },
  navInner: {
    display: 'flex',
    gap: 4,
    background: 'rgba(255,255,255,0.08)',
    ...GLASS_NAV,
    border: '1px solid rgba(255,255,255,0.14)',
    borderRadius: 22,
    padding: 5,
    boxShadow: '0 8px 32px rgba(0,0,0,0.45), inset 0 1px 0 rgba(255,255,255,0.08)',
  },
  navBtn: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    color: 'rgba(245,247,250,0.55)',
    fontFamily: "'Inter', sans-serif",
    fontSize: 9,
    fontWeight: 600,
    letterSpacing: '0.3px',
    textTransform: 'uppercase',
    padding: '10px 4px',
    whiteSpace: 'nowrap',
    position: 'relative',
    borderRadius: 17,
    transition: 'color 0.2s, background 0.2s',
    minWidth: 0,
  },
  navBtnCart: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  navBtnActive: {
    color: '#0A0A0F',
    background: GOLD,
    boxShadow: '0 2px 12px rgba(204,255,0,0.45)',
  },
  navCartBadge: {
    marginLeft: 6,
    background: PURPLE_BROWN,
    color: GOLD,
    fontSize: 10,
    fontWeight: 700,
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 4px',
  },
  navCartBadgeUrgent: {
    background: '#FF3D5A',
    color: '#FFFFFF',
  },
  main: {
    maxWidth: 480,
    margin: '0 auto',
    padding: '28px 20px 0',
    position: 'relative',
    zIndex: 2,
  },
  eyebrowSection: {
    fontSize: 9,
    letterSpacing: '3px',
    textTransform: 'uppercase',
    color: RUST,
    margin: '0 0 6px',
    fontWeight: 500,
  },
  sectionTitle: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontSize: 24,
    fontWeight: 400,
    color: PURPLE_DARK,
    margin: '0 0 18px',
  },
  searchWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    background: SURFACE,
    border: 1.5px solid ${GOLD_LIGHT},
    borderRadius: 14,
    padding: '13px 14px',
    marginBottom: 4,
  },
  searchInput: {
    flex: 1,
    border: 'none',
    outline: 'none',
    fontSize: 16,
    fontFamily: "'Inter', sans-serif",
    background: 'transparent',
    color: PURPLE_DARK,
  },
  clearBtn: {
    border: 'none',
    background: 'transparent',
    padding: 2,
    display: 'flex',
  },
  resultsList: {
    marginTop: 10,
    animation: 'slideUp 0.15s ease',
  },
  resultRow: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: SURFACE,
    border: 1px solid rgba(255,255,255,0.25),
    borderRadius: 12,
    padding: '13px 14px',
    marginBottom: 8,
    fontSize: 15,
    fontFamily: "'Inter', sans-serif",
    color: PURPLE_DARK,
    textAlign: 'left',
  },
  resultName: { fontWeight: 500 },
  resultMeta: { display: 'flex', alignItems: 'center', gap: 10 },
  unitTag: {
    fontSize: 10,
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
    color: RUST,
    background: '#1C1C26',
    padding: '3px 9px',
    borderRadius: 20,
    fontWeight: 500,
  },
  resultRowActive: {
    width: '100%',
    background: '#1C1C26',
    border: 1.5px solid ${GOLD},
    borderRadius: 12,
    padding: '12px 14px',
    marginBottom: 8,
  },
  resultRowUrgent: {
    background: '#1F1418',
    borderColor: '#FF3D5A',
  },
  resultActiveTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  resultActiveBottom: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  newRow: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    background: '#1C1C26',
    border: 1px dashed ${RUST},
    borderRadius: 12,
    padding: '13px 14px',
    fontSize: 14,
